Our first system of equation:

$$2x+7y-z= 9$$
$$x-3y+z = 5$$
$$-4x+y+z = -3$$

Solve for x,y,z

In [1]:
import numpy as np

In [60]:
A = np.array([[2,7,-1],
              [1,-3,1],
              [-4,1,1]])

In [61]:
b = np.array([9,5,-3])

The above system of equation can be written in the form of
$$Ax = b$$

And the solution is: $A^{-1}b$

In [62]:
sol = np.linalg.inv(A).dot(b)
sol

array([2.75  , 1.4375, 6.5625])

In [63]:
np.linalg.solve(A,b)

array([2.75  , 1.4375, 6.5625])

In [64]:
A_aug = np.c_[A,b]
A_aug = A_aug.astype(np.float32)
A_aug

array([[ 2.,  7., -1.,  9.],
       [ 1., -3.,  1.,  5.],
       [-4.,  1.,  1., -3.]], dtype=float32)

In [65]:
A_aug_1 = A_aug.copy()
A_aug_1[1,:] = A_aug[0,:]
A_aug_1[0,:] = A_aug[1,:]
A_aug_1

array([[ 1., -3.,  1.,  5.],
       [ 2.,  7., -1.,  9.],
       [-4.,  1.,  1., -3.]], dtype=float32)

In [66]:
# Make cell values below cell (0,0) to 0
# R_2 = -2R_1 + R_2
A_aug_1[1,:] = -2*A_aug_1[0,:] + A_aug_1[1,:]
A_aug_1

array([[ 1., -3.,  1.,  5.],
       [ 0., 13., -3., -1.],
       [-4.,  1.,  1., -3.]], dtype=float32)

In [67]:
A_aug_1[2,:] = 4*A_aug_1[0,:] + A_aug_1[2,:]
A_aug_1

array([[  1.,  -3.,   1.,   5.],
       [  0.,  13.,  -3.,  -1.],
       [  0., -11.,   5.,  17.]], dtype=float32)

In [68]:
A_aug_1[1,:] = (1/A_aug_1[1,1])*A_aug_1[1,:]
A_aug_1

array([[  1.        ,  -3.        ,   1.        ,   5.        ],
       [  0.        ,   1.        ,  -0.23076925,  -0.07692308],
       [  0.        , -11.        ,   5.        ,  17.        ]],
      dtype=float32)

In [69]:
A_aug_1[2,:] = 11*A_aug_1[1,:] + A_aug_1[2,:]
A_aug_1

array([[ 1.        , -3.        ,  1.        ,  5.        ],
       [ 0.        ,  1.        , -0.23076925, -0.07692308],
       [ 0.        ,  0.        ,  2.4615383 , 16.153847  ]],
      dtype=float32)

In [70]:
A_aug_1[2,:] = (1/A_aug_1[2,2])*A_aug_1[2,:]
A_aug_1

array([[ 1.        , -3.        ,  1.        ,  5.        ],
       [ 0.        ,  1.        , -0.23076925, -0.07692308],
       [ 0.        ,  0.        ,  1.        ,  6.562501  ]],
      dtype=float32)

In [71]:
A_aug_1[1,:] = (-1)*A_aug_1[1,2]*A_aug_1[2,:] + A_aug_1[1,:]
A_aug_1

array([[ 1.       , -3.       ,  1.       ,  5.       ],
       [ 0.       ,  1.       ,  0.       ,  1.4375002],
       [ 0.       ,  0.       ,  1.       ,  6.562501 ]], dtype=float32)

In [72]:
A_aug_1[0,:] = (-1)*A_aug_1[0,2]*A_aug_1[2,:] + A_aug_1[0,:]
A_aug_1

array([[ 1.       , -3.       ,  0.       , -1.562501 ],
       [ 0.       ,  1.       ,  0.       ,  1.4375002],
       [ 0.       ,  0.       ,  1.       ,  6.562501 ]], dtype=float32)

In [73]:
A_aug_1[0,:] = (-1)*A_aug_1[0,1]*A_aug_1[1,:] + A_aug_1[0,:]
A_aug_1

array([[1.       , 0.       , 0.       , 2.75     ],
       [0.       , 1.       , 0.       , 1.4375002],
       [0.       , 0.       , 1.       , 6.562501 ]], dtype=float32)

In [74]:
A_aug_2 = A_aug.copy()

In [75]:
row, col = A_aug_2.shape
(row, col)

(3, 4)

In [76]:
# A_aug_1[1,:] = -2*A_aug_1[0,:] + A_aug_1[1,:]
# A_aug_1

In [84]:
# Forward operations
A_aug_2 = A_aug.copy()

for step in range(row): #[0,1,2]
    print("step:",step)
    
    # If pivot cell value is 0, swap rows such that it stays non zero
    
    if A_aug_2[step,step] != 0:
        A_aug_2[step,:] = A_aug_2[step,:]*(1/A_aug_2[step,step])
    else: # swap rows
        r1 = A_aug_2[step,:].copy()
        for r in range(step+1, row):
            if A_aug_2[r,step] !=0:
                A_aug_2[step,:] = A_aug_2[r,:]
                A_aug_2[r,:] = r1
                A_aug_2[step,:] = A_aug_2[step,:]*(1/A_aug_2[step,step])
                break
            else:
                continue
                
    print("A_aug:\n",A_aug_2)
    for r in range(step+1,row):
#         print('r:',r)
        A_aug_2[r,:] = (-1)*A_aug_2[r,step]*A_aug_2[step,:] + A_aug_2[r,:] 
        print("A_aug:\n", A_aug_2)
        
# Backward substitution
for step in range(row-1,-1,-1): # [2,1,0]
    for r in range(step-1,-1, -1):
        print('r:',r)
        A_aug_2[r,:] = (-1)*A_aug_2[r,step]*A_aug_2[step,:] + A_aug_2[r,:]
        print("A_aug:\n", A_aug_2)

# A_aug_2

step: 0
A_aug:
 [[ 1.   3.5 -0.5  4.5]
 [ 1.  -3.   1.   5. ]
 [-4.   1.   1.  -3. ]]
A_aug:
 [[ 1.   3.5 -0.5  4.5]
 [ 0.  -6.5  1.5  0.5]
 [-4.   1.   1.  -3. ]]
A_aug:
 [[ 1.   3.5 -0.5  4.5]
 [ 0.  -6.5  1.5  0.5]
 [ 0.  15.  -1.  15. ]]
step: 1
A_aug:
 [[ 1.          3.5        -0.5         4.5       ]
 [-0.          1.         -0.23076925 -0.07692308]
 [ 0.         15.         -1.         15.        ]]
A_aug:
 [[ 1.          3.5        -0.5         4.5       ]
 [-0.          1.         -0.23076925 -0.07692308]
 [ 0.          0.          2.4615388  16.153847  ]]
step: 2
A_aug:
 [[ 1.          3.5        -0.5         4.5       ]
 [-0.          1.         -0.23076925 -0.07692308]
 [ 0.          0.          1.          6.562499  ]]
r: 1
A_aug:
 [[ 1.         3.5       -0.5        4.5      ]
 [ 0.         1.         0.         1.4374999]
 [ 0.         0.         1.         6.562499 ]]
r: 0
A_aug:
 [[1.        3.5       0.        7.7812495]
 [0.        1.        0.        1.4374999]
 [

In [85]:
def solve_Gauss_elim(aug_mat):
    A_aug_2 = aug_mat.copy()

    for step in range(row): #[0,1,2]
#         print("step:",step)
    
    # If pivot cell value is 0, swap rows such that it stays non zero
    
        if A_aug_2[step,step] != 0:
            A_aug_2[step,:] = A_aug_2[step,:]*(1/A_aug_2[step,step])
        else: # swap rows
            r1 = A_aug_2[step,:].copy()
            for r in range(step+1, row):
                if A_aug_2[r,step] !=0:
                    A_aug_2[step,:] = A_aug_2[r,:]
                    A_aug_2[r,:] = r1
                    A_aug_2[step,:] = A_aug_2[step,:]*(1/A_aug_2[step,step])
                    break
                else:
                    continue
                
#         print("A_aug:\n",A_aug_2)
        for r in range(step+1,row):
#         print('r:',r)
            A_aug_2[r,:] = (-1)*A_aug_2[r,step]*A_aug_2[step,:] + A_aug_2[r,:] 
#             print("A_aug:\n", A_aug_2)
        
# Backward substitution
    for step in range(row-1,-1,-1): # [2,1,0]
        for r in range(step-1,-1, -1):
#             print('r:',r)
            A_aug_2[r,:] = (-1)*A_aug_2[r,step]*A_aug_2[step,:] + A_aug_2[r,:]
#             print("A_aug:\n", A_aug_2)
    return A_aug_2

In [92]:
solve_Gauss_elim(np.array([[0,1,5,5],[2,0,7,12],[1,1,-2,-1]]).astype(np.float32))

array([[ 1.        ,  0.        ,  0.        ,  2.        ],
       [ 0.        ,  1.        ,  0.        , -0.71428585],
       [-0.        , -0.        ,  1.        ,  1.1428572 ]],
      dtype=float32)

In [90]:
A1 = np.array([[0,1,5,5],[2,0,7,12],[1,1,-2,-1]])

In [91]:
np.linalg.inv(A1[:,:3]).dot(A1[:,3])

array([ 2.        , -0.71428571,  1.14285714])